apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-interview-backend
  namespace: ai-agent-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-backend
  template:
    metadata:
      labels:
        app: ai-backend
    spec:
      containers:
        - name: backend
          image: asif1993/ai-interview-backend:v2
          ports:
            - containerPort: 8000
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: all-secrets-here
                  key: GROQ_API_KEY
